
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int define = 2;
  public static final int coma = 8;
  public static final int mult = 14;
  public static final int numeric_integer_const = 17;
  public static final int divreal = 16;
  public static final int vvoid = 6;
  public static final int numeric_real_const = 18;
  public static final int vfloat = 10;
  public static final int menos = 13;
  public static final int diventera = 15;
  public static final int ident = 22;
  public static final int constlit = 19;
  public static final int igual = 20;
  public static final int EOF = 0;
  public static final int aperturaLlaves = 5;
  public static final int cierreParentesis = 4;
  public static final int vint = 9;
  public static final int vreturn = 21;
  public static final int error = 1;
  public static final int cierreLlaves = 7;
  public static final int aperturaParentesis = 3;
  public static final int mas = 12;
  public static final int punto_coma = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "define",
  "aperturaParentesis",
  "cierreParentesis",
  "aperturaLlaves",
  "vvoid",
  "cierreLlaves",
  "coma",
  "vint",
  "vfloat",
  "punto_coma",
  "mas",
  "menos",
  "mult",
  "diventera",
  "divreal",
  "numeric_integer_const",
  "numeric_real_const",
  "constlit",
  "igual",
  "vreturn",
  "ident"
  };
}

